title: "Tutoriales LIB"
description: "Laboratorio de Invasiones Biológicas — Curso de análisis espacial y modelado ecológico"
theme: minima
markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false
    css_class: 'highlight'

highlighter: rouge
