title: "Tutoriales LIB"
description: "Laboratorio de Invasiones Biológicas — Curso de análisis espacial y modelado ecológico"
theme: just-the-docs

# Config extra para just-the-docs
search_enabled: true
color_scheme: light
aux_links:
  "Laboratorio de Invasiones Biológicas (LIB)"
  
